### ISSUE TITLE
Rot13 Decode/Encode

### ISSUE THREAD

**Issue by Karrq** [Quickscript-Competiton/July2020entries#1]
## Code
Found at this [gist](https://gist.github.com/Karrq/24617dd24ff63b047211444b49099956).

## Licence 
Present in gist. Same as Racket: MIT/Apache 2

## Contact details 
Karrq on racket slack
Karrq#0636 on discord

**Comment by spdegabrielle** [comment]
Gunax lbh @Karrq

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
