### ISSUE TITLE
design-recipe-template - builds a simple design recipe template for a function whose name is highlighted

### ISSUE THREAD

**Issue by smtuttle** [Quickscript-Competiton/July2020entries#11]
Please enter the competition here:

## code
https://gist.github.com/smtuttle/8464a8c887ea89c6e5f0ebfd8e4ae6ae

## Licence 
Apache 2/MIT

## contact details 
best: smtuttle@alumni.rice.edu
still learning slack: sharon.tuttle@humboldt.edu

**Comment by Metaxal** [comment]
Nice! Sounds like you could have used this script to write your previous script :)

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
