### ISSUE TITLE
CVE Search

### ISSUE THREAD

**Issue by robertpostill** [Quickscript-Competiton/July2020entries#12]
Please enter the competition here:

## code
https://gist.github.com/robertpostill/a268e0439be8226662474ce46c279d75

## Licence  
Apache 2/MIT 

## contact details 
robertpostill  on racket slack

**Comment by spdegabrielle** [comment]
@robertpostill Awesome! Thank you!

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
