### ISSUE TITLE
[ Extract colorscheme to package ] Creates a new "info.rkt" in the directory of your choosing with the current colorscheme as a new package. 

### ISSUE THREAD

**Issue by soapdog** [Quickscript-Competiton/July2020entries#13]
Please enter the competition here:

## code
https://gist.github.com/soapdog/8e660225178962cf09a95279f7408861

## Licence 
MIT

## contact details 
Andre Garzia (on Racket Slack)

**Comment by Metaxal** [comment]
Nice!

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
