### ISSUE TITLE
visit-url-at-insertion-point

### ISSUE THREAD

**Issue by rfindler** [Quickscript-Competiton/July2020entries#16]
Please enter the competition here:

## code
https://gist.github.com/rfindler/ee4e4c2f04e01c162fd234579efdf95c

## Licence 
[CC-BY](https://creativecommons.org/licenses/by/4.0/)

## contact details 
robby@racket-lang.org

**Comment by Metaxal** [comment]
Very nice, with tests and all!

Small glitch: The windows/unix `visit-url-at-insertion-point/windows-unix` script function misses the `selection` argument when calling `visit-url-at-insertion-point`.
(Or rather, it seems that `visit-url-at-insertion-point` should not accept the `selection` argument and the macos script function must be updated too.)

**Comment by rfindler** [comment]
Thanks! I've tried to fix those things (and it also handles the "there is no url here" case better now too).

**Comment by Metaxal** [comment]
Great, thanks Robby!

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser

**Comment by rfindler** [comment]
Thank you!
