### ISSUE TITLE
Script for sorting lines in source files

### ISSUE THREAD

**Issue by shriram** [Quickscript-Competiton/July2020entries#18]
Please enter the competition here:

## code
https://gist.github.com/shriram/5e79c6935849926e2148c5f42a43209f

## Licence 
Apache 2/MIT

## contact details 
@ShriramKMurthi on Twitter, @shriram on GitHub

**Comment by Metaxal** [comment]
Wonderful!
May I suggest using `#:menu-path ("Sort lines")` just below each `#:label ...` so that all the functions are grouped under one common submenu?

**Comment by shriram** [comment]
You certainly may! Thank you. I've updated it, and it looks a lot nicer now. QuickScript is amazing, btw — chapeau !

**Comment by Metaxal** [comment]
Excellent, thanks! And with tests :)
Glad you like Quickscript!

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
