### ISSUE TITLE
Preview markdown file in a web browser

### ISSUE THREAD

**Issue by tfidfwastaken** [Quickscript-Competiton/July2020entries#19]
## code
https://gist.github.com/tfidfwastaken/29ade7eef652665ce20ccd5019a05714

## Licence 
Apache 2/MIT

## contact details 
racket slack: atharva

**Comment by Metaxal** [comment]
That's very useful, thanks!

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
