### ISSUE TITLE
cs111-course-links.rkt - playing with a very-simple course-specific submenu

### ISSUE THREAD

**Issue by smtuttle** [Quickscript-Competiton/July2020entries#22]
Please enter the competition here:

## code
https://gist.github.com/smtuttle/49cbcf6f3b6448f5da1ccf1ffb607615

## Licence 
Apache 2/MIT

## contact details 
Racket Slack: Sharon Tuttle, email: sharon.tuttle@humboldt.edu; (also smtuttle@alumni.rice.edu

**Comment by Metaxal** [comment]
This can be useful! Too bad it requires authentication, I wanted to take a peek :)

**Comment by smtuttle** [comment]
Only the Canvas submenu link should require authentication -- the other 3 should not (unless there is something I am missing, which would not be surprising! XD)

**Comment by Metaxal** [comment]
Indeed the other work. May I suggest "Canvas course site (restricted access)" for the first label then?

**Comment by smtuttle** [comment]
Excellent idea! I have made this improvement.

Thanks!

— Sharon

--
Sharon M. Tuttle, Professor
Department of Computer Science
Humboldt State University, Arcata, CA
sharon.tuttle@humboldt.edu
