### ISSUE TITLE
Your scripts are bundled in a package!

### ISSUE THREAD

**Issue by Metaxal** [Quickscript-Competiton/July2020entries#24]
@robertpostill @soapdog @rfindler @smtuttle @hasn0life @bennn @tfidfwastaken @shriram @sorawee @spdegabrielle @soegaard @Metaxal @alex-hhh @Lambduli @Karrq 

Hi everyone!

Your quickscript has been bundled into [this package](https://github.com/Quickscript-Competiton/July2020entries) (look at the script subdirectory), and each license and author has been added at the top of each file along with a `script-help-string`. Some cosmetic modifications may have been made, and some scripts have been moved to submenus to reduce clutter. Please take a look and let us know for any of your scripts if 
* you prefer your script to not be packaged or 
* you want to fix something in it (you can send pull requests or by replying to the corresponding script entry/issue).

The package will be publicized Friday evening (tomorrow, UK time), so please send us your feedback soon if you have any. After that, we will reach out to Racket users—including you—to vote for their favourite scripts!

You will still be able to make/request changes to the bundled scripts afterwards of course.

**Comment by Metaxal** [comment]
And finally the package is [here](https://pkgs.racket-lang.org/package/quickscript-competition-2020)!

**Comment by robertpostill** [comment]
Thanks :)

**Comment by robertpostill** [comment]
@sorawee WRT the license.  I notice its MIT or apache2.  Are you asking me if I want to decide one or the other or that it's dual-licensed?

**Comment by sorawee** [comment]
It's the same as Racket. You can choose whichever you want.

**Comment by robertpostill** [comment]
Thanks, just wanted to check.

**Comment by Metaxal** [comment]
You can choose the dual MIT/Apache2 license too, which means that the ones building on your work can also choose either or both.
