### ISSUE TITLE
Contact details and Survey

### ISSUE THREAD

**Issue by spdegabrielle** [Quickscript-Competiton/July2020entries#25]
@robertpostill @soapdog @rfindler @smtuttle @hasn0life @bennn @tfidfwastaken @shriram @sorawee @spdegabrielle @soegaard @Metaxal @alex-hhh @Lambduli @Karrq

Thank you for entering the Quickscript competition!

Please use this form to provide postal details and feedback: https://forms.gle/dNBaZEQnFAqmGWGv6

Individual details will only be used to send prizes. Survey comments will used to improve future events. All responses are confidential and will not be shared with any third party. Retention period ends 31 Dec 2020 at with point the database will be deleted.

Each participant is entitled to a T-shirt and stickers, but don't enter any size if you don't want the T-shirt.

Note: Not 'asos' shirts but the size charts should be approximately correct - please use 'other' and provide a note if you have any concerns.
https://www.asos.com/discover/size-charts/women/
https://www.asos.com/discover/size-charts/men/tshirts-polo-shirts/

**Comment by Metaxal** [comment]
Quick reminder :slightly_smiling_face:  Also, all feedback is welcome (in particular constructive criticism), so we can know how to do it better next time, either for Quickscript or for some other aspect of Racket. Thank you all!

**Comment by smtuttle** [comment]
Lauren —

I think I filled out the contact details and survey — but please let me know if I am mistaken/if my response was not received.

Thanks!

— Sharon

--
Sharon M. Tuttle, Professor
Department of Computer Science
Humboldt State University, Arcata, CA
sharon.tuttle@humboldt.edu

**Comment by Metaxal** [comment]
Yes, we received your answers, thank you!

**Comment by Metaxal** [comment]
Just a heads-up that the prizes will take a little time to arrive (busy busy...), but they will arrive eventually :) The stickers are already with me. Thanks for your patience!

**Comment by soapdog** [comment]
@Metaxal can you post photos of them? I am soooo curious :D

**Comment by Metaxal** [comment]
Here you go:
![IMG_20200812_135957 (1)](https://user-images.githubusercontent.com/1658140/91565381-076a3f80-e93a-11ea-9729-aed89f039228.jpg)

**Comment by Metaxal** [comment]
Update: I received the T-shirts (yay!), I'll send everything within a week. Then it may take a week or so to arrive.

**Comment by Metaxal** [comment]
All posted! Please let me know if you haven't received anything in two weeks. Apologies for the time it took and thank you all for participating in the Quickscript Competition 2020!

**Comment by spdegabrielle** [comment]
T-shirt received - looks good!

**Comment by Karrq** [comment]
Just got my stuff in the mail! Thank you!! Looks great! <3

**Comment by soapdog** [comment]
Got my stuff! I'm using it right now! Thanks a ton <3 <3 <3

![image](https://user-images.githubusercontent.com/23247/94794077-4a08b700-03d3-11eb-8bca-49352307ec41.png)

**Comment by smtuttle** [comment]
Woo hoo! The most-excellent Quickscript competition goodies made their way all the way to Arcata, CA as of today!

Thank you muchly! I plan to show them off to my intro programming Zoom labs tomorrow! 8 - )

— Sharon Tuttle

--
Sharon M. Tuttle, Professor
Department of Computer Science
Humboldt State University, Arcata, CA
sharon.tuttle@humboldt.edu

**Comment by robertpostill** [comment]
Just to say I received my goodies, thanks! :)
