### ISSUE TITLE
Format-selection

### ISSUE THREAD

**Issue by alex-hhh** [Quickscript-Competiton/July2020entries#3]
Please enter the competition here:

The script will format the selected text to wrap around a 78 character limit.  It is able to detect comments and format them accordingly:

![fill-paragraph](https://user-images.githubusercontent.com/11592690/86784762-78a51900-c094-11ea-9d90-5c09b0380470.gif)

## code
URL for repo or gist, or paste below

https://gist.github.com/alex-hhh/9577db5c936161546c1a730028491145

## Licence 
[Your choice: We suggest using the same as Racket: Apache 2/MIT ]

MIT

## contact details 
racket slack / IRC / discord handle

@alex-hhh

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
