### ISSUE TITLE
Open Racket news and events in the browser.

### ISSUE THREAD

**Issue by spdegabrielle** [Quickscript-Competiton/July2020entries#8]
Please enter the competition here:

## code

https://gist.github.com/spdegabrielle/ec5b3759654c5f1a1656c477062700f0

## Licence 
same as Racket: Apache 2/MIT

## contact details 
spdegabrielle

**Comment by Metaxal** [comment]
Can you make it a gist, so I can link to a raw file for the `competition-2020-scripts.rkt`?

**Comment by spdegabrielle** [comment]
done
